### ISSUE TITLE
FBM

### ISSUE THREAD

**Issue by ghost** [amz-tools/amazon-sp-api#11] opened 2020-12-29 05:37 UTC
Hallo...
I sell my product by email. so how can I inform amazon(FBM) by API ? my product is delivered.

**Comment by amz-tools** [comment] 2020-12-29 13:35
Hi @ShubhamSharma1998 

you would use the **createShipment** operation, [see reference here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/merchant-fulfillment-api/merchantFulfillmentV0.md#createshipment).

You don't need to inform the customer, Amazon will automatically do so when createShipment has been called successfully.

Quote from Amazon docs: "Orders shipped using Merchant Fulfilment API are auto-confirmed. When you call the CreateShipment method, the customer receives automatically an order confirmation".

**Comment by ShubhamSharma1998** [comment] 2020-12-29 14:06
thanks, sir for your valuable reply.
As you said we need to call createShipment Api. And this Api requires two paramater ShipmentRequestDetails, ShippingServiceId,
So I think we need to call getEligibleShipmentServices first because getEligibleShipmentServices returns ShippingServiceList(which contains ShippingServiceId).
To call getEligibleShipmentServices API we requires ShipmentRequestDetails object .Schema for this object requires
AmazonOrderId,ItemList,ShipFromAddress,PackageDimensions,weight.
And each  PackageDimensions requires Length, Width,Height,Unit
#Issue is our order is delivered by email. so we have no weight Etc.....

**Comment by amz-tools** [comment] 2020-12-29 14:20
Ah okay, didn't get that right the first time. I am not familiar with fulfilling digital content via API, but I would think this should be possible with the messaging API, maybe have a look at the [createDigitalAccessKey operation](https://github.com/amzn/selling-partner-api-docs/blob/main/references/messaging-api/messaging.md#createdigitalaccesskey) and/or the other operations in the messaging section.

**Comment by amz-tools** [comment] 2021-01-16 19:24
@ShubhamSharma1998 Did you succeed? Can we close this issue?

**Closed** 2021-03-31 22:20 UTC
