### ISSUE TITLE
sellingpartner.endpoints() issue

### ISSUE THREAD

**Issue by benisdp** [amz-tools/amazon-sp-api#133] opened 2022-05-19 20:21 UTC
Is anyone else having problems using this function? I'm trying to get a list of all the supported endpoints and when I try to call this on SellingPartner.endpoints() OR sellingPartner.endpoints() (an instance stored in a variable), It says 'endpoint' does not exist on type sellingPartner.

**Comment by amz-tools** [comment] 2022-05-22 19:48
Hi @benisdp,

it should work fine. Maybe the issue is that you are calling it as a function `sellingPartner.endpoints()`, but its just a simple getter so you would call it without the brackets: `sellingPartner.endpoints`

**Comment by benisdp** [comment] 2022-05-22 20:59
Thanks, that did it. As a heads up, heres a screenshot of how it comes up in VS. It gave me an error so that's why i was confused, maybe it can be added on as a property of sellingPartner.
<img width="710" alt="Screen Shot 2022-05-22 at 4 54 47 PM" src="https://user-images.githubusercontent.com/53890189/169715567-df447bb6-1ba7-4dd9-90f1-55ab0e3ae348.png">

**Comment by amz-tools** [comment] 2022-05-23 08:18
This is probably because the `endpoints` getter is not yet defined in `index.d.ts`. Feel free to add it and submit a PR and we will include it in the next version. Will close this for the time being.

**Closed by amz-tools** 2022-05-23 08:18 UTC

**Comment by bryandunbar** [comment] 2024-10-22 23:03
I'm still getting this error on the latest build 1.2.2. Am I doing something wrong?
