### ISSUE TITLE
listCatalogItems request rate limit with "Query" 

### ISSUE THREAD

**Issue by ahmetsametoglu** [amz-tools/amazon-sp-api#78] opened 2021-12-10 16:07 UTC
Hi,

I've really interesting results about the rate limit for `operation: 'catalogItems.listCatalogItems'`. According to [selling-partner-api](https://github.com/amzn/selling-partner-api-docs/blob/ab4fac0fec129720c47221914928dde57dde9f7f/references/catalog-items-api/catalogItemsV0.md); rate limit is 6 request per second. So, we can call this request for every 167 ms. 

When I test rate-limit with the following code, I didn't get any error for 126 requests. 
counter: `{request: 126, response: 126, error: 0}`

``` ts
import SellingPartnerAPI from 'amazon-sp-api';

const sellingPartner = new SellingPartnerAPI({
  options: {
    auto_request_throttled: false,
  },
  ...defaultASPConfig, // sellerId, region, credentials, refresh_token
});

const counter = { request: 0, response: 0, error: 0 };
const timeout = 167;

const testRequest = () => {
  counter.request++;
  sellingPartner
    .callAPI({
      operation: 'catalogItems.listCatalogItems',
      query: { MarketplaceId: 'A1PA6795UKMFR9', EAN: '4008789094032' },
    })
    .then(() => counter.response++)
    .catch(err => {
      console.log(err);
      counter.error++;
    })
    .finally(() => console.log(counter));
};

setInterval(testRequest, timeout);
```

Everything as expected **BUT** when I call this request with _**Query**_ like as below

```ts

const counter = { request: 0, response: 0, error: 0 };
const timeout = 167;

const testRequest = () => {
  counter.request++;
  sellingPartner
    .callAPI({
      operation: 'catalogItems.listCatalogItems',
      query: { MarketplaceId: 'A1PA6795UKMFR9', Query: '4008789094032' },
    })
    .then(() => counter.response++)
    .catch(err => {
      console.log(err);
      counter.error++;
    })
    .finally(() => console.log(counter));
};

setInterval(testRequest, timeout);
```

the result is `{request: 126, response: 39, error: 87}` and I have got this message `You exceeded your quota for the requested resource.` for every error.

_**Moreover**_

I got different results by changing the timeout parameter,
for `const timeout = 500;`, counter: `{request: 100, response: 16, error: 84}` 
for `const timeout = 1000;`, counter: `{request: 100, response: 29, error: 71}` 

I reviewed it dozens of times, but I couldn't see my mistake. Are you (@amz-tools) getting the same result?

**Comment by amz-tools** [comment] 2021-12-11 20:10
Hi @ahmetsametoglu,

we are also still having trouble with the restore rates for some operations, including `listCatalogItems`. Your tests look a lot like results we are getting as well. But what we haven't noticed yet is a case where the params of the request actually change the rate-limit.

I am not really wondering that your first test did not fire any `QuotaExceeded` errors. `listCatalogItems` has a burst of 40 on that operation, so you could theoretically initialize 40 requests in parallel and then have the timeout, but since you start right away with the timeout the bucket is not emptied very fast.

But is it possible that you started the 2nd test right after the 1st one? Because to us it seems as if Amazon is not refilling these buckets with requests in time, at least not in the time of 6 per second. So if you started the 2nd test right away after the 1st one, the bucket is not filled with the 40 requests yet and a `QuotaExceeded` error is fired pretty fast.

Also another thing we noticed: It seems as if a request is also "counting" when it fails with a `QuotaExceeded` error. So if you request too fast and get an error, it seems as if Amazon is somehow "resetting" the refill time (in this case 167ms), which could finally end in an infinite `QuotaExceeded` loop. You could try that by i.e. setting the timeout to 100ms and then let it run, it should end up in an infinite error loop pretty fast.

Just to have it mentioned, there is also the possibility of seller accounts having lower rate limits than the default. These are found in the `x-amzn-ratelimit-limit` header. For our accounts we can rule out that this is causing the issues, though. The header ratelimit stayed the same with 6 requests per second. If you want to read the header value with the client, you would have to pass `raw_result:true` inside the options object of `.callAPI()`.

Please let us know if you notice anything else or different or if you find a good solution of how to handle these rate limit issues.

**Comment by ahmetsametoglu** [comment] 2021-12-12 01:01
I have improved my test, here is the result:
```
startTime: (ms) test start time
finishTime: (ms) test end time
testDuration: (ms) test time
idleTime: (ms) the time between the end of the previous test and the beginning of the current test
expectedBurst: approximately burst
resetBurstRequestCount: number of request to reset burst
idType: query type  //EAN - Query
timeout: waiting time between two test requests
firstErrorRequest: index of the request that gave the first quota error
request: count of request
response: count of a successful response
error: count of an error response
```

![image](https://user-images.githubusercontent.com/48984129/145696148-27c678c9-f71e-4220-9cb2-48c8cb7dfa92.png)

2 clear results:
- Rate limit changes when **idType** is a **Query**.
- selling-partner-api is slippy. (That's why I'm going to lose all my hair soon)


**Test Code**
```ts
const resetRequest = () =>
  sellingPartner.callAPI({
    operation: 'catalogItems.listCatalogItems',
    query: { MarketplaceId: 'A1PA6795UKMFR9', EAN: '4008789094032' },
  });

let resetBurstRequestCount = 0;
const resetBurst = async () => {
  resetBurstRequestCount = 0;
  let isBurstReset = false;
  while (!isBurstReset) {
    try {
      await Promise.all([resetRequest(), resetRequest(), resetRequest()]);
      resetBurstRequestCount += 3;
    } catch (error) {
      if (error.code === 'QuotaExceeded') isBurstReset = true;
    }
  }
};

let interval;

let startTime;
let finishTime;
let previousTestFinishTime;
let firstErrorRequest;
let idType;
let timeout;
const counter = { request: 0, response: 0, error: 0 };

const reportParameters = [
  { idType: 'EAN', timeout: 500 },
  { idType: 'EAN', timeout: 500 },
  { idType: 'Query', timeout: 500 },
  { idType: 'Query', timeout: 500 },
  { idType: 'EAN', timeout: 500 },
  { idType: 'EAN', timeout: 500 },
  { idType: 'EAN', timeout: 500 },
  { idType: 'EAN', timeout: 167 },
  { idType: 'EAN', timeout: 167 },
  { idType: 'EAN', timeout: 167 },
  { idType: 'EAN', timeout: 167 },
];
const reports = [];

const createReport = () => {
  const idleTime = previousTestFinishTime ? startTime - previousTestFinishTime : null;
  const testDuration = finishTime - startTime;
  const newReport = {
    no: reports.length + 1,
    startTime,
    finishTime,
    testDuration,
    idleTime,
    expectedBurst: idleTime ? Math.round(idleTime / 167) : null,
    resetBurstRequestCount,
    idType,
    timeout,
    firstErrorRequest,
    request: counter.request,
    response: counter.response,
    error: counter.error,
  };

  console.clear();
  reports.push(newReport);
  console.table(reports);

  if (reportParameters.length > 0) setTimeout(startTest, 5000);
};

const testRequest = () => {
  counter.request++;

  const query = { MarketplaceId: 'A1PA6795UKMFR9' };
  query[idType] = '4008789094032';
  sellingPartner
    .callAPI({ operation: 'catalogItems.listCatalogItems', query })
    .then(() => counter.response++)
    .catch(err => {
      if (err.code === 'QuotaExceeded') {
        counter.error++;
        if (counter.error === 1) {
          firstErrorRequest = counter.error + counter.response;
        }
      }
    })
    .finally(() => {
      if (counter.response + counter.error === 100) {
        clearInterval(interval);
        interval = null;

        finishTime = new Date().getTime();
        createReport();
        previousTestFinishTime = finishTime;
      }
    });
};

const startTest = async () => {
  const nextTestParameter = reportParameters.pop();
  idType = nextTestParameter.idType;
  timeout = nextTestParameter.timeout;

  //reset variables
  firstErrorRequest = 0;
  counter.error = 0;
  counter.request = 0;
  counter.response = 0;
  console.log(`test started: id-type:${idType} timeout:${timeout}`);

  await resetBurst();
  setTimeout(() => {
    startTime = new Date().getTime() + timeout;
    interval = setInterval(testRequest, timeout);
  }, 1000);
};

startTest();
```

**Comment by ahmetsametoglu** [comment] 2021-12-12 01:24
and header has a rate limit field: `x-amzn-ratelimit-limit:'6.0'`

**Comment by amz-tools** [comment] 2021-12-13 11:12
Hi @ahmetsametoglu,

that's really strange! Apparently the rate limit really changes when changing the `idType`. Even more fun: I have tested your script with 3 different accounts and ALL accounts have 100% success rate for EVERY test. So it seems the issue is account dependent as well...that doesn't really help to find a good solution that fits every account I guess.

**Comment by ahmetsametoglu** [comment] 2021-12-16 07:33
Case Response;
What does it mean `hourly quota`?
I didn't see anything about it on selling-partner-documentation.

```Throttling occurs because you reached the maximum request quota. Each operation has its own set quota, which can be viewed on their documentation pages. Throttling can occur in one of two ways.

1. You can make requests too frequently, which will prevent successful requests, but won’t count towards your request quota. The solution for this is to space out the number of requests so that they occur according to the refresh rate of the quota.
2. You can utilize all of your quota. Once you have utilized all of your hourly quota, you will not be able to make any more requests within the hour. This is based off of a rolling hour.

Some of our most common throttling scenarios occur by using the Orders and Products APIs too frequently. These issues can be resolved by utilizing our Reports section to retrieve orders, and the AnyOfferChangedNotification to keep abreast of price changes. We cannot provide a throttling increase and recommend following the best practices as listed below in our documentation on our Developer website to ensure you have a scalable software.

Throttling limits are listed under the API documentation, generally under the heading of each section. For instance, for the Products API you can find all throttling information at: http://docs.developer.amazonservices.com/en_UK/products/Products_Throttling.html.

If it's not under the heading, you can check the specific operation and often the throttling limits are in the first couple paragraphs. We cannot provide a throttling increase and recommend following the best practices as listed below in addition to documentation on our Developer website to ensure you have a scalable software. Best practices:
1. Avoid submitting a lot of feeds with only a few records in each feed. When possible, combine the data into less frequent larger feeds.
2. Include only the products you are updating, not your entire inventory.
3. Upload one feed of the same type no more than once every 20 minutes. Allow more time between larger feeds.
4. Keep file size below 10 MB

For more information, please visit:
Throttling http://docs.developer.amazonservices.com/en_US/dev_guide/DG_Throttling.html

Reports Section: http://docs.developer.amazonservices.com/en_US/reports/Reports_Overview.html

AnyOfferChangedNotification- http://docs.developer.amazonservices.com/en_US/notifications/Notifications_AnyOfferChangedNotification.html```

**Comment by ahmetsametoglu** [comment] 2021-12-16 17:13
```
My name is Dylan from Amazon Developer Support.

In the sp-api, for one operation, the rate limited should be the same even if you only change the type of parameter. In the sp-api, in the header of the respond, we have x-amzn-RateLimit-Limit: to show the current rate limit , from the Github page, it looks like your x-amzn-RateLimit-Limit is 6.0 which is the same as our documentation. And our server will not give you the x-amzn-RateLimit-Limit : 6.0 if your current rate limit is not 6.0 .

So if you see that in the respond of the header is x-amzn-RateLimit-Limit : 6.0 you may continue to talk with amz_tools who provide the module, as this is out of amazon scope, because maybe it is something wrong need to be change for the JS module. and our official module do not contain JS library.

Thank you for selling with Amazon.
```

@amz-tools your test is 100%, right?

**Comment by amz-tools** [comment] 2021-12-17 11:43
@ahmetsametoglu, yes, tried three different accounts and all of them gave 100% success rate with your script. But we do have issues when we run our scripts for a long time (i.e. for a couple of hours). Even when we "over-respect" the restore rate, i.e. setting it to 500ms per request. It will start throttling (which it really shouldn't) and it sometimes even results in infinite loop, which should be impossible according to this answer from Amazon:

> You can make requests too frequently, which will prevent successful requests, but won’t count towards your request quota. The solution for this is to space out the number of requests so that they occur according to the refresh rate of the quota.

So feeling a bit lost here...did you grasp the whole hourly quota topic? We can't really make anything out of that answer from Amazon...

**Comment by amz-tools** [comment] 2022-10-23 22:19
Will close this for now for the following reasons:

No more updates on the topic for quite some time
The original tested method `listCatalogItems` is already deprecated
Amazon seems to follow the given restore rates nowadays a lot more than it used to be when we discussed this

**Closed by amz-tools** 2022-10-23 22:19 UTC
