### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by DoogieStick** [amz-tools/amazon-sp-api#125] opened 2022-04-07 14:20 UTC
When I try to restock. I tried everything, even I used the example on the npm link and always I got the message 
The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by amz-tools** [comment] 2022-04-07 16:18
Hi @DoogieStick,

could you post your request here? And which version of the client are you using?

**Comment by DoogieStick** [comment] 2022-04-07 19:01
"use strict";
const SellingPartnerAPI = require('amazon-sp-api');

const sellingPartner = new SellingPartnerAPI({
    region: 'na', // The region to use for the SP-API endpoints ("eu", "na" or "fe")
    refresh_token: process.env.REFRESH_TOKEN,
    credentials: {
        SELLING_PARTNER_APP_CLIENT_ID: process.env.SELLING_PARTNER_APP_CLIENT_ID,
        SELLING_PARTNER_APP_CLIENT_SECRET: process.env.SELLING_PARTNER_APP_CLIENT_SECRET,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_SELLING_PARTNER_ROLE: process.env.AWS_SELLING_PARTNER_ROLE
    }
});

var controllers = {

    submitRestockFeed: async function (req, res) {

        try {

            let feed = {
                content:`<?xml version="1.0" encoding="utf-8"?>
                  <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
                    <Header>
                      <DocumentVersion>1.02</DocumentVersion>
                      <MerchantIdentifier>${process.env.MERCHANT_ID}</MerchantIdentifier>
                    </Header>
                    <MessageType>Inventory</MessageType>
                    <Message>
                      <MessageID>1</MessageID>
                      <Inventory>
                        <SKU>${req.body.sku}</SKU>
                        <Quantity>${req.body.quantity}</Quantity>
                      </Inventory>
                    </Message>
                  </AmazonEnvelope>`,
                contentType:'text/xml; charset=utf-8'
              };
            
            let feed_upload_details = await sellingPartner.callAPI({
                operation:'createFeedDocument',
                endpoint:'feeds',
                body:{
                  contentType:feed.contentType
                }
            });

            let resUpload = await sellingPartner.upload(feed_upload_details, feed);

            console.info("feed_doc ", feed_upload_details)
            console.info("feed ", feed)
            console.info("upload ", resUpload)

            let feed_creation_infos = await sellingPartner.callAPI({
                operation:'createFeed',
                endpoint:'feeds',
                body:{
                  marketplaceIds:['ATVPDKIKX0DER'],
                  feedType:'POST_INVENTORY_AVAILABILITY_DATA',
                  inputFeedDocumentId:feed_upload_details.feedDocumentId // retrieve the feedDocumentId from the "createFeedDocument" operation
                }
            });

            console.info("feed doc ", feed_creation_infos)

            res.send(feed_creation_infos)

        } catch (e) {
            console.info(e);
            let response = {
                status: "-1",
                error: e
            }
            res.json(response);
        }
    }



};

module.exports = controllers;



This is my whole controller, but basically I followed the example from npm site. I was using the version 0.6.5, but after started receiving this error I already updated and downgraded the version, but I continue getting same error (the credentials are OK because operations as create and get reports are working perfectly).

**Comment by amz-tools** [comment] 2022-04-08 18:48
Closing this, as this issue is a duplicate of ticket #124 and discussed there.

**Closed by amz-tools** 2022-04-08 18:48 UTC
