### ISSUE TITLE
 User: arn:aws:i am::871271927410:user/24stream is not authorized to perform: sts:AssumeRole on r esource: arn:aws:iam::871271927410:role/24StreamRole

### ISSUE THREAD

**Issue by ipirm** [amz-tools/amazon-sp-api#170] opened 2022-10-09 18:07 UTC
Getting Error while start application. and call first api.

import { Injectable } from "@nestjs/common";
import { CreateAmazonDto } from "./dto/create-amazon.dto";
import { UpdateAmazonDto } from "./dto/update-amazon.dto";

const SellingPartnerAPI = require("amazon-sp-api");

@Injectable()
export class AmazonService {
  constructor() {

  }

  create(createAmazonDto: CreateAmazonDto) {
    return "This action adds a new amazon";
  }

  async findAll(): Promise<any> {
    const sellingPartner = new SellingPartnerAPI({
      region: "eu",
      refresh_token: "Atzr|IwEBIEMj6s_hgMOWE_5Dyk-I6gV5B7piw8J6nRYPx9F9CpmlGXlcfWWQEohAJeByjTvE_MFVKoQmCvNNLwjeQYnBft20C4T0r1AazPp81JA5m8diQW05Kh1bP8iotq2QBdx-U1klugGfQm5kuT8IaGAvDX8u894E0zn5qx-htJvIlkmOLcvPihfAY0Q-FTLPzWyhNapTc_VBO0Zoi7jB_qeJ_oxF0RdZTGMHt-jsyanij-Ygv_I_-gXe16oTwemtNWSEofVvI7uFbmh2_HLRpA5uYw8C6CdxgwKYggNWe4TwJTzvbLMpxxhACH1eb6dDxDaQweg",
      credentials: {
        SELLING_PARTNER_APP_CLIENT_ID: process.env.SELLING_PARTNER_APP_CLIENT_ID,
        SELLING_PARTNER_APP_CLIENT_SECRET: process.env.SELLING_PARTNER_APP_CLIENT_SECRET,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_SELLING_PARTNER_ROLE: process.env.AWS_SELLING_PARTNER_ROLE
      },
      options: {
        debug_log: true
      }
    });
    console.log(sellingPartner);
    // console.log(sellingPartner);
    const token = await sellingPartner.access_token;
    // const role = await sellingPartner.refreshRoleCredentials();
    // let res = await sellingPartner.callAPI({
    //   operation: "getMarketplaceParticipations",
    //   endpoint: "sellers"
    // });
    let res = await sellingPartner.callAPI({
      operation: "getMarketplaceParticipations",
      endpoint: ""
    });

    // console.log(res);

    console.log(token);
    return res;
  }

  findOne(id: number) {
    return `This action returns a #${id} amazon`;
  }

  update(id: number, updateAmazonDto: UpdateAmazonDto) {
    return `This action updates a #${id} amazon`;
  }

  remove(id: number) {
    return `This action removes a #${id} amazon`;
  }
}

**Comment by ipirm** [comment] 2022-10-09 18:07
![image](https://user-images.githubusercontent.com/48025760/194772572-c19492f9-b2a0-4e13-ae50-63fe59c9ee9e.png)

**Comment by nothinman** [comment] 2022-10-15 21:11
the issue is with IAM permissions...

**Comment by amz-tools** [comment] 2023-10-29 15:51
Closed as wontfix/invalid as signing is not necessary anymore.

**Closed by amz-tools** 2023-10-29 15:51 UTC
